version: '3.10'

services:
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'

    env_file:
      - db.env

    volumes:
      - ./data/db:/var/lib/postgresql/data/

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend: 
    depends_on:
      db:
        condition: service_healthy

    build: 
      context: ./HydroponicSystem
      dockerfile: Dockerfile

    ports:
      - '8000:8000'

    volumes:
      - ./HydroponicSystem:/app/HydroponicSystem